- id: 1129
  name: "GAMEFRAME_FIXED"
- id: 1130
  name: "GAMEFRAME_RESIZABLE_BOX"
- id: 1131
  name: "GAMEFRAME_RESIZABLE_LINE"
- id: 1132
  name: "GAMEFRAME_BLACK_SCREEN"
- id: 1981
  name: "SPELLBOOK"
- id: 1982
  name: "NORMAL_SPELLBOOK"
- id: 1983
  name: "ANCIENT_SPELLBOOK"
- id: 1984
  name: "LUNAR_SPELLBOOK"
- id: 1985
  name: "ARCEUUS_SPELLBOOK"
