/*
 * Copyright 2018-2020 Guthix
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Dont EDIT! This file is automatically generated by io.guthix.oldscape.server.cache.CodeGenerator. */
package io.guthix.oldscape.server.template.api

import io.guthix.oldscape.cache.config.EnumConfig
import io.guthix.oldscape.cache.config.EnumConfig.*
import io.guthix.oldscape.server.template.ConfigTemplateLoader

@Suppress("UNCHECKED_CAST")
object EnumTemplates : ConfigTemplateLoader<EnumConfig<Any, Any>>() {
    val GAMEFRAME_FIXED: Map<Component, Component> = get(1129) as Map<Component, Component>
    val GAMEFRAME_RESIZABLE_BOX: Map<Component, Component> = get(1130) as Map<Component, Component>
    val GAMEFRAME_RESIZABLE_LINE: Map<Component, Component> = get(1131) as Map<Component, Component>
    val GAMEFRAME_BLACK_SCREEN: Map<Component, Component> = get(1132) as Map<Component, Component>
    val NORMAL_SPELLBOOK: Map<Int, Int> = get(1982) as Map<Int, Int>
    val ANCIENT_SPELLBOOK: Map<Int, Int> = get(1983) as Map<Int, Int>
    val LUNAR_SPELLBOOK: Map<Int, Int> = get(1984) as Map<Int, Int>
    val ARCEUUS_SPELLBOOK: Map<Int, Int> = get(1985) as Map<Int, Int>
    val SPELLBOOK: Map<Int, Map<Int, Int>> = mapOf(
        0 to NORMAL_SPELLBOOK,
        1 to ANCIENT_SPELLBOOK,
        2 to LUNAR_SPELLBOOK,
        3 to ARCEUUS_SPELLBOOK,
    )
}
