val ktSerVersion: String by extra("1.0.1")
val kamlVersion: String by extra("0.26.0")
val nettyVersion: String by extra("4.1.42.Final")
val exposedVersion: String by extra("0.28.1")
val postgresVersion: String by extra("42.2.18")