- ids:
  - 24794
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24798
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24802
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24806
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24810
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24814
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24818
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24822
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24826
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24830
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24834
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24838
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
