- ids:
  - 24796
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24800
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24804
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24808
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24812
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24816
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24820
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24824
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24828
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24832
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24836
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
- ids:
  - 24840
  weight: 0.907
  examine: "Lets you dress like a vampyre noble."
  equipment:
    attackBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    defenceBonus:
      stab: 0
      slash: 0
      crush: 0
      magic: 0
      range: 0
    strengthBonus:
      melee: 0
      range: 0
      magic: 0
    prayerBonus: 0
