/*
 * Copyright 2018-2021 Guthix
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.guthix.oldscape

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.plugins.JavaPlugin
import org.gradle.api.tasks.SourceSetContainer

abstract class CodeGenerator : Plugin<Project> {
    override fun apply(target: Project) {
        createGeneratedDir(target)
    }

    fun createGeneratedDir(target: Project) {
        target.plugins.withType(JavaPlugin::class.java) {
            val sourceSets = target.properties["sourceSets"] as SourceSetContainer
            sourceSets.getByName("main").java.srcDir(GENERATED_FOLDER)
        }
    }

    companion object {
        const val GENERATED_FOLDER: String = "src/main/generated"

        val warningHeader: String =
            "/* Dont EDIT! This file is automatically generated by ${CodeGenerator::class.qualifiedName}. */"
    }
}